# Generated by Django 5.0.1 on 2024-01-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_description_freelancer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='portfolio',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='skills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
