# Generated by Django 5.0.1 on 2024-01-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_username_freelancer_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
