# Generated by Django 5.0.1 on 2024-01-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_freelancer_phone_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='username',
        ),
    ]
