# Generated by Django 5.0.1 on 2024-01-31 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_client_company_name_client_description_client_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='client',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='username',
        ),
    ]
